### turn on drone (physical)
POST http://localhost:1234/turn_on HTTP/1.1
content-type: application/json
auth: very-secure-token

{
    "charge":"100"
}


### drone status

GET http://localhost:1234/status HTTP/1.1

### drone status from mobile

POST http://localhost:9876/drone_status HTTP/1.1
content-type: application/json
auth: very-secure-token

{
    "PIN":"1234",
    "drone_password": "password"
}

### drone to home

POST http://localhost:9876/drone_to_home HTTP/1.1
content-type: application/json
auth: very-secure-token

{
    "PIN":"1234",
    "drone_password": "password"
}

### mobile make drone worked (turn on by mobile). PIN to mobile

POST http://localhost:9876/drone_work HTTP/1.1
content-type: application/json
auth: very-secure-token

{
    "PIN":"1234",
    "drone_password": "password"
}

### add task to control center

POST http://localhost:5050/add_task HTTP/1.1
content-type: application/json
auth: very-secure-token

{
    "X_start":"7",
    "Y_start":"8",
    "Z_start":"3",
    "X_end":"9000",
    "Y_end":"9",
    "Z_end":"6",
    "sign": "IvanovII"
}



### bad task
POST http://localhost:5050/add_task HTTP/1.1
content-type: application/json
auth: very-secure-token

{
    "X_start":"10",
    "Y_start":"",
    "Z_start":"",
    "X_end":"po",
    "Y_end":"",
    "Z_end":""
}

### cheat request for bad GPS
GET http://localhost:1234/bad_GPS HTTP/1.1

### log about incident

GET http://localhost:5050/incident_info HTTP/1.1

