@startuml

participant Drone as "Дрон"

participant Mobile as "МП"
participant CC as "УЦ"
actor "Оператор УЦ" as u_cc

u_cc -> CC: добавили задания в пул
note over CC #red
Задания изменены или 
созданы новые
end note
Mobile -> Drone: запуск для работы
Drone -> CC: запрос задания
CC --[#red]> Drone: неверное или небезопасное задание
CC --[#red]> Mobile: неверное или небезопасное задание
Drone -> Drone: проверили задание
note left #red
Задания подделаны так,
что дрон не может
это определить
end note

Drone -> Drone++: работает 
note left #red
Небезопасное задание
end note
Drone -> Mobile: сообщение о завершении
Drone -> CC--: сообщение о завершении
Drone -> Drone: возвращение домой



@enduml